// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface MathUtils$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "MathUtils";
  readonly sourceName: "contracts/libraries/MathUtils.sol";
  readonly abi: [];
  readonly bytecode: "0x6080806040523460175760399081601c823930815050f35b5f80fdfe5f80fdfea264697066735822122099b51afea8a7d5e052bc44423fb9359f9061a53c59091b1b867258befa9eb92864736f6c634300081c0033";
  readonly deployedBytecode: "0x5f80fdfea264697066735822122099b51afea8a7d5e052bc44423fb9359f9061a53c59091b1b867258befa9eb92864736f6c634300081c0033";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/libraries/MathUtils.sol";
  readonly buildInfoId: "solc-0_8_28-e503b6cb7e36f6a2da9265ae68aa3172e7b24b3d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["MathUtils"]: MathUtils$Type;
    ["contracts/libraries/MathUtils.sol:MathUtils"]: MathUtils$Type;
  }
}