// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface ILiquidationManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "ILiquidationManager";
  readonly sourceName: "contracts/interfaces/ILiquidationManager.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"checkFreezeStatus","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"checkLockStatus","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/ILiquidationManager.sol";
  readonly buildInfoId: "solc-0_8_28-e503b6cb7e36f6a2da9265ae68aa3172e7b24b3d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["ILiquidationManager"]: ILiquidationManager$Type;
    ["contracts/interfaces/ILiquidationManager.sol:ILiquidationManager"]: ILiquidationManager$Type;
  }
}