// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IInterestManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IInterestManager";
  readonly sourceName: "contracts/interfaces/IInterestManager.sol";
  readonly abi: [{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"}],"name":"previewAccruedInterest","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"uint256","name":"sAmountInWei","type":"uint256"},{"internalType":"uint256","name":"lAmountInWei","type":"uint256"}],"name":"recordPosition","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"user","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"uint256","name":"burnPercentageInBps","type":"uint256"}],"name":"updatePosition","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IInterestManager.sol";
  readonly buildInfoId: "solc-0_8_28-e503b6cb7e36f6a2da9265ae68aa3172e7b24b3d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IInterestManager"]: IInterestManager$Type;
    ["contracts/interfaces/IInterestManager.sol:IInterestManager"]: IInterestManager$Type;
  }
}