// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IAuctionManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IAuctionManager";
  readonly sourceName: "contracts/interfaces/IAuctionManager.sol";
  readonly abi: [{"inputs":[{"internalType":"uint256","name":"valueToBeBurned","type":"uint256"},{"internalType":"address","name":"originalOwner","type":"address"},{"internalType":"uint256","name":"tokenId","type":"uint256"},{"internalType":"uint256","name":"underlyingValueToUser","type":"uint256"},{"internalType":"address","name":"triggerer","type":"address"}],"name":"startAuction","outputs":[{"internalType":"uint256","name":"auctionId","type":"uint256"}],"stateMutability":"nonpayable","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IAuctionManager.sol";
  readonly buildInfoId: "solc-0_8_28-e503b6cb7e36f6a2da9265ae68aa3172e7b24b3d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IAuctionManager"]: IAuctionManager$Type;
    ["contracts/interfaces/IAuctionManager.sol:IAuctionManager"]: IAuctionManager$Type;
  }
}