// This file was autogenerated by Hardhat, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable
// biome-ignore format: see above

export interface IOracleManager$Type {
  readonly _format: "hh3-artifact-1";
  readonly contractName: "IOracleManager";
  readonly sourceName: "contracts/interfaces/IOracleManager.sol";
  readonly abi: [{"inputs":[],"name":"getLatestPriceView","outputs":[{"internalType":"uint256","name":"price","type":"uint256"},{"internalType":"uint256","name":"timestamp","type":"uint256"},{"internalType":"bool","name":"isValid","type":"bool"}],"stateMutability":"view","type":"function"}];
  readonly bytecode: "0x";
  readonly deployedBytecode: "0x";
  readonly linkReferences: {};
  readonly deployedLinkReferences: {};
  readonly immutableReferences: {};
  readonly inputSourceName: "project/contracts/interfaces/IOracleManager.sol";
  readonly buildInfoId: "solc-0_8_28-e503b6cb7e36f6a2da9265ae68aa3172e7b24b3d";
};

import "hardhat/types/artifacts";
declare module "hardhat/types/artifacts" {
  interface ArtifactMap {
    ["IOracleManager"]: IOracleManager$Type;
    ["contracts/interfaces/IOracleManager.sol:IOracleManager"]: IOracleManager$Type;
  }
}